# Generated by Django 5.1.4 on 2025-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='capacite_fiscale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='codgeo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='densite_medicale_bv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='dynamique_demographique_insee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='dynamique_entrepreneuriale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='dynamique_entrepreneuriale_service_et_commerce',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='evolution_pop_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='indice_demographique',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='indice_menages',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='indice_synergie_medicale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='latitude_centre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='libgeo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='longitude_centre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='med14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_apparts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_camping',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_commerces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_construction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_entreprises',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_industrielles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_services',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_de_commerce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_de_services_aux_particuliers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_dentistes_liberaux_bv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_education_sante_action_sociale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_commerce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_construction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_industrie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_services',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_hotel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_infirmiers_liberaux_bv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_institution_de_education_sante_action_sociale_administration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_log_vacants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_logement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_logement_secondaire_et_occasionnel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_maisons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_menages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_mutations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_omnipraticiens_bv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_pharmaciens_liberaux_bv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_proprietaire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_residences_principales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_residences_secondaires',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_sante_action_sociale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_services_personnels_et_domestiques',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_batiments_historique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_cinemas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_crime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_ecole',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_festivals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_gare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_hopitaux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nombre_musees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_chom1524',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_chom1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_chom2554',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop0014',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop1524',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop1529',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop1564',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop2554',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop3044',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop4559',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop6074',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop7589',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop90p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='prix_m2_moyen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='prix_moyen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='propappart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='propmaison',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='score_croissance_entrepreneuriale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='score_croissance_population',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='surface_moy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='synergie_medicale_commune',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='taux_propriete',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
