# Generated by Django 5.1.4 on 2025-01-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0002_alter_commune_capacite_fiscale_alter_commune_codgeo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nb_mutations',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
