# Generated by Django 5.1.4 on 2025-01-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0003_alter_commune_nb_mutations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nb_apparts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_camping',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_commerces',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_construction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_entreprises',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_industrielles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_creation_services',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_de_commerce',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_de_services_aux_particuliers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_dentistes_liberaux_bv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_education_sante_action_sociale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_commerce',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_construction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_industrie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_entreprises_secteur_services',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_hotel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_infirmiers_liberaux_bv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_institution_de_education_sante_action_sociale_administration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_log_vacants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_logement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_logement_secondaire_et_occasionnel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_maisons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_menages',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_omnipraticiens_bv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_pharmaciens_liberaux_bv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_proprietaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_residences_principales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_residences_secondaires',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_sante_action_sociale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nb_services_personnels_et_domestiques',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
