# Generated by Django 5.1.4 on 2025-01-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0004_alter_commune_nb_apparts_alter_commune_nb_camping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='p21_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop0014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop1524',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop1529',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop2554',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop3044',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop4559',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop6074',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop7589',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='p21_pop90p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
