# Generated by Django 5.1.4 on 2025-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0005_alter_commune_p21_pop_alter_commune_p21_pop0014_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code_oaci', models.CharField(blank=True, max_length=10, null=True)),
                ('code_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude_aeroport', models.FloatField()),
                ('longitude_aeroport', models.FloatField()),
                ('ville', models.CharField(max_length=255)),
            ],
        ),
    ]
