# Generated by Django 5.1.4 on 2025-02-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0006_aeroport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('combustible', models.CharField(max_length=255)),
                ('sous_filiere', models.CharField(max_length=255)),
                ('date_mise_en_service', models.DateField()),
                ('puissance_installee', models.FloatField()),
                ('puissance_minimum', models.FloatField()),
                ('reserve_secondaire', models.FloatField()),
                ('region', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('latitude_centrale', models.FloatField()),
                ('longitude_centrale', models.FloatField()),
            ],
        ),
    ]
