# Generated by Django 5.1.4 on 2025-02-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0007_centrale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centrale',
        ),
    ]
