# Generated by Django 5.1.4 on 2025-02-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0010_hopital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hopital',
        ),
    ]
