# Generated by Django 5.1.4 on 2025-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0011_delete_hopital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude_hopital', models.FloatField()),
                ('longitude_hopital', models.FloatField()),
            ],
        ),
    ]
