# Generated by Django 5.1.4 on 2025-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0012_hopital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('latitude_ecole', models.FloatField()),
                ('longitude_ecole', models.FloatField()),
                ('secteur', models.CharField(blank=True, max_length=50, null=True)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_commune', models.CharField(max_length=100)),
            ],
        ),
    ]
