import pandas as pd
from django.core.management.base import BaseCommand
from visualisation.models import Commune

class Command(BaseCommand):
    help = 'Import data from df_communes.csv'

    def handle(self, *args, **kwargs):
        file_path = 'df_communes.csv'
        data = pd.read_csv(file_path)
        for _, row in data.iterrows():
            Commune.objects.create(
                codgeo=row.get('CODGEO', None),
                libgeo=row.get('LIBGEO', None),
                med14=row.get('MED14', None),
                nombre_batiments_historique=row.get('nombre_batiments_historique', None),
                nombre_hopitaux=row.get('nombre_hopitaux', None),
                nombre_crime=row.get('nombre_crime', None),
                nombre_ecole=row.get('nombre_ecole', None),
                p21_pop=row.get('P21_POP', None),
                p21_pop0014=row.get('P21_POP0014', None),
                p21_pop1529=row.get('P21_POP1529', None),
                p21_pop3044=row.get('P21_POP3044', None),
                p21_pop4559=row.get('P21_POP4559', None),
                p21_pop6074=row.get('P21_POP6074', None),
                p21_pop7589=row.get('P21_POP7589', None),
                p21_pop90p=row.get('P21_POP90P', None),
                p21_pop1564=row.get('P21_POP1564', None),
                p21_pop1524=row.get('P21_POP1524', None),
                p21_pop2554=row.get('P21_POP2554', None),
                p21_chom1564=row.get('P21_CHOM1564', None),
                p21_chom1524=row.get('P21_CHOM1524', None),
                p21_chom2554=row.get('P21_CHOM2554', None),
                nombre_cinemas=row.get('nombre_cinemas', None),
                nombre_musees=row.get('nombre_musees', None),
                nombre_festivals=row.get('nombre_festivals', None),
                nb_mutations=row.get('Nb_mutations', None),
                nb_maisons=row.get('NbMaisons', None),
                nb_apparts=row.get('NbApparts', None),
                propmaison=row.get('propmaison', None),
                propappart=row.get('propappart', None),
                prix_moyen=row.get('PrixMoyen', None),
                prix_m2_moyen=row.get('Prixm2Moyen', None),
                surface_moy=row.get('SurfaceMoy', None),
                nombre_gare=row.get('nombre_gare', None),
                dynamique_entrepreneuriale=row.get('Dynamique Entrepreneuriale', None),
                dynamique_entrepreneuriale_service_et_commerce=row.get('Dynamique Entrepreneuriale Service et Commerce', None),
                synergie_medicale_commune=row.get('Synergie Médicale COMMUNE', None),
                indice_synergie_medicale=row.get('Indice Synergie Médicale', None),
                nb_omnipraticiens_bv=row.get('Nb Omnipraticiens BV', None),
                nb_infirmiers_liberaux_bv=row.get('Nb Infirmiers Libéraux BV', None),
                nb_dentistes_liberaux_bv=row.get('Nb dentistes Libéraux BV', None),
                nb_pharmaciens_liberaux_bv=row.get('Nb pharmaciens Libéraux BV', None),
                densite_medicale_bv=row.get('Densité Médicale BV', None),
                indice_demographique=row.get('Indice Démographique', None),
                indice_menages=row.get('Indice Ménages', None),
                evolution_pop_percent=row.get('Evolution Pop %', None),
                nb_menages=row.get('Nb Ménages', None),
                nb_residences_principales=row.get('Nb Résidences Principales', None),
                nb_proprietaire=row.get('Nb propriétaire', None),
                nb_logement=row.get('Nb Logement', None),
                nb_residences_secondaires=row.get('Nb Résidences Secondaires', None),
                nb_log_vacants=row.get('Nb Log Vacants', None),
                nb_entreprises_secteur_services=row.get('Nb Entreprises Secteur Services', None),
                nb_entreprises_secteur_commerce=row.get('Nb Entreprises Secteur Commerce', None),
                nb_entreprises_secteur_construction=row.get('Nb Entreprises Secteur Construction', None),
                nb_entreprises_secteur_industrie=row.get('Nb Entreprises Secteur Industrie', None),
                nb_creation_entreprises=row.get('Nb Création Enteprises', None),
                nb_creation_industrielles=row.get('Nb Création Industrielles', None),
                nb_creation_construction=row.get('Nb Création Construction', None),
                nb_creation_commerces=row.get('Nb Création Commerces', None),
                nb_creation_services=row.get('Nb Création Services', None),
                nb_logement_secondaire_et_occasionnel=row.get('Nb Logement Secondaire et Occasionnel', None),
                nb_hotel=row.get('Nb Hotel', None),
                nb_camping=row.get('Nb Camping', None),
                taux_propriete=row.get('Taux Propriété', None),
                dynamique_demographique_insee=row.get('Dynamique Démographique INSEE', None),
                capacite_fiscale=row.get('Capacité Fiscale', None),
                nb_education_sante_action_sociale=row.get('Nb Education, santé, action sociale', None),
                nb_services_personnels_et_domestiques=row.get('Nb Services personnels et domestiques', None),
                nb_sante_action_sociale=row.get('Nb Santé, action sociale', None),
                nb_de_commerce=row.get('Nb de Commerce', None),
                nb_de_services_aux_particuliers=row.get('Nb de Services aux particuliers', None),
                nb_institution_de_education_sante_action_sociale_administration=row.get('Nb institution de Education, santé, action sociale, administration', None),
                score_croissance_population=row.get('Score Croissance Population', None),
                score_croissance_entrepreneuriale=row.get('Score Croissance Entrepreneuriale', None),
                longitude_centre=row.get('longitude_centre', None),
                latitude_centre=row.get('latitude_centre', None),
            )
