field_labels = {
    "codgeo": "Code géographique",
    "libgeo": "Nom de la commune",
    "med14": "Niveau médian de vie (2014)",
    "nombre_batiments_historique": "Nombre de bâtiments historiques",
    "nombre_hopitaux": "Nombre d'hôpitaux",
    "nombre_crime": "Nombre de crimes",
    "nombre_ecole": "Nombre d'écoles",
    "p21_pop": "Population totale",
    "p21_pop0014": "Population âgée de 0 à 14 ans",
    "p21_pop1529": "Population âgée de 15 à 29 ans",
    "p21_pop3044": "Population âgée de 30 à 44 ans",
    "p21_pop4559": "Population âgée de 45 à 59 ans",
    "p21_pop6074": "Population âgée de 60 à 74 ans",
    "p21_pop7589": "Population âgée de 75 à 89 ans",
    "p21_pop90p": "Population âgée de 90 ans et plus",
    "p21_pop1564": "Population en âge de travailler (15-64 ans)",
    "p21_pop1524": "Population jeune (15-24 ans)",
    "p21_pop2554": "Population active (25-54 ans)",
    "p21_chom1564": "Taux de chômage (15-64 ans)",
    "p21_chom1524": "Taux de chômage des jeunes (15-24 ans)",
    "p21_chom2554": "Taux de chômage des adultes (25-54 ans)",
    "nombre_cinemas": "Nombre de cinémas",
    "nombre_musees": "Nombre de musées",
    "nombre_festivals": "Nombre de festivals",
    "nb_mutations": "Nombre de mutations immobilières",
    "nb_maisons": "Nombre de maisons",
    "nb_apparts": "Nombre d'appartements",
    "propmaison": "Proportion de maisons",
    "propappart": "Proportion d'appartements",
    "prix_moyen": "Prix moyen immobilier",
    "prix_m2_moyen": "Prix moyen au mètre carré",
    "surface_moy": "Surface moyenne des logements",
    "nombre_gare": "Nombre de gares",
    "dynamique_entrepreneuriale": "Dynamique entrepreneuriale",
    "dynamique_entrepreneuriale_service_et_commerce": "Dynamique entrepreneuriale (services et commerce)",
    "synergie_medicale_commune": "Synergie médicale",
    "indice_synergie_medicale": "Indice de synergie médicale",
    "nb_omnipraticiens_bv": "Nombre d'omnipraticiens",
    "nb_infirmiers_liberaux_bv": "Nombre d'infirmiers libéraux",
    "nb_dentistes_liberaux_bv": "Nombre de dentistes libéraux",
    "nb_pharmaciens_liberaux_bv": "Nombre de pharmaciens libéraux",
    "densite_medicale_bv": "Densité médicale",
    "indice_demographique": "Indice démographique",
    "indice_menages": "Indice des ménages",
    "evolution_pop_percent": "Évolution de la population (%)",
    "nb_menages": "Nombre de ménages",
    "nb_residences_principales": "Nombre de résidences principales",
    "nb_proprietaire": "Nombre de propriétaires",
    "nb_logement": "Nombre de logements",
    "nb_residences_secondaires": "Nombre de résidences secondaires",
    "nb_log_vacants": "Nombre de logements vacants",
    "nb_entreprises_secteur_services": "Nombre d'entreprises dans le secteur des services",
    "nb_entreprises_secteur_commerce": "Nombre d'entreprises dans le secteur du commerce",
    "nb_entreprises_secteur_construction": "Nombre d'entreprises dans le secteur de la construction",
    "nb_entreprises_secteur_industrie": "Nombre d'entreprises dans le secteur industriel",
    "nb_creation_entreprises": "Nombre de créations d'entreprises",
    "nb_creation_industrielles": "Nombre de créations d'entreprises industrielles",
    "nb_creation_construction": "Nombre de créations d'entreprises de construction",
    "nb_creation_commerces": "Nombre de créations d'entreprises commerciales",
    "nb_creation_services": "Nombre de créations dans les services",
    "nb_logement_secondaire_et_occasionnel": "Nombre de logements secondaires ou occasionnels",
    "nb_hotel": "Nombre d'hôtels",
    "nb_camping": "Nombre de campings",
    "taux_propriete": "Taux de propriété",
    "dynamique_demographique_insee": "Dynamique démographique (INSEE)",
    "capacite_fiscale": "Capacité fiscale",
    "nb_education_sante_action_sociale": "Nombre dans éducation, santé et action sociale",
    "nb_services_personnels_et_domestiques": "Nombre dans les services personnels et domestiques",
    "nb_sante_action_sociale": "Nombre dans santé et action sociale",
    "nb_de_commerce": "Nombre d'établissements de commerce",
    "nb_de_services_aux_particuliers": "Nombre de services aux particuliers",
    "nb_institution_de_education_sante_action_sociale_administration": "Nombre d'institutions (éducation, santé, administration)",
    "score_croissance_population": "Score de croissance de la population",
    "score_croissance_entrepreneuriale": "Score de croissance entrepreneuriale",
    "longitude_centre": "Longitude du centre",
    "latitude_centre": "Latitude du centre",
}
